### ISSUE TITLE
Units should be able to embark on water past a certain science level

### ISSUE THREAD

**Issue by haltode** [haltode/Pacification#48]
- [x] Implement the functionality (bd3c00d7624918602a6d9378b4fb1c98c6811112)
- [ ] This action should be possible only past a certain science level
- [x] Add a boat 3D model
- [x] Take this into account in pathfinding values

**Comment by Nickname666** [comment]
Or by building docks

**Comment by DaSpood** [comment]
@haltode Need to adapt the pathfinding so units cannot go on water when not embarked, otherwise they just don't turn into boats and go there anyway

**Comment by haltode** [comment]
very hard 27d6203b277ba13b31bd0f45cea94b480325e9bd
