### ISSUE TITLE
Fix displayers & add city-only displayers and menus

### ISSUE THREAD

**Issue by DaSpood** [haltode/Pacification#62]
- [x] Remove happiness and production from global displayers
- [x] Add happiness, production, population as per-city displayer
- [x] Add horses, wood, steel, gold, diamond as global displayers
- [x] Add city menu to build buildings, similar to barracks (buttons should call the "City.Build" function with the correct string parameter)

**Comment by Nickname666** [comment]
1f78ede

**Comment by Nickname666** [comment]
c230ca0

**Comment by Nickname666** [comment]
cf95f16
