### ISSUE TITLE
Adapt pathfinding to limit the amount of moves per turn

### ISSUE THREAD

**Issue by DaSpood** [haltode/Pacification#65]
Each travelled tile must increase the Unit.currMVT counter.
Once the counter is equal to the value of Unit.mvtSPD, the unit must not be able to move anymore:
     -If currently travelling, the move action must stop immediately.
     -If the unit is stopped, either the pathfinding must be disabled until next turn for that specific unit, or the move action must not start.
     -Idealy (but optional), the pathfinding must either stop or change color beyond the move limit, so the player does not expect to be able to move further than he actualy can.

Each new turn resets the unit's counter.
The counter and it's reset are already done.

**Comment by haltode** [comment]
See 31fe91f4aaf013649d0a6dfbf7a0e801137585b6 and 024a30978b7bc8e3aac7dd0fbc63ab9846c744ff.
