### ISSUE TITLE
Graphic bug when impossible pathfinding

### ISSUE THREAD

**Issue by Nickname666** [haltode/Pacification#7]
When selecting a unit and creating an impossible path,
![image](https://user-images.githubusercontent.com/34349557/39563015-c4939076-4eae-11e8-9543-3ddd3b1635eb.png)
the hexagon color surounding the unit stays even when clicking on another cell.
![image](https://user-images.githubusercontent.com/34349557/39563036-d95f7c68-4eae-11e8-8113-81674262895c.png)
It only disapear when selecting another unit and making it move.
![image](https://user-images.githubusercontent.com/34349557/39563081-07b86c8c-4eaf-11e8-9dbd-11e56dc5c33c.png)
![image](https://user-images.githubusercontent.com/34349557/39563088-13774016-4eaf-11e8-8ff5-643db2ac16db.png)

**Comment by haltode** [comment]
Fixed in https://github.com/haltode/Pacification/commit/b9c87f12fdc9f5ab7b0adf9ffa91877e9539395f.
